// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9XtBTdIkCaz9_x7ihuLLCefNDzH3VKE',
    appId: '1:407000492909:web:316c059afddc00eedf8864',
    messagingSenderId: '407000492909',
    projectId: 'studyquest-fb520',
    authDomain: 'studyquest-fb520.firebaseapp.com',
    storageBucket: 'studyquest-fb520.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDpWcb98lFtOnagUayJr_0n1Of63Kpo4',
    appId: '1:407000492909:android:53318f6abd7a63aadf8864',
    messagingSenderId: '407000492909',
    projectId: 'studyquest-fb520',
    storageBucket: 'studyquest-fb520.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp6iS4pznQylFkSMSa9RwFrrg03HM0U8o',
    appId: '1:407000492909:ios:6812796a78389ef4df8864',
    messagingSenderId: '407000492909',
    projectId: 'studyquest-fb520',
    storageBucket: 'studyquest-fb520.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp6iS4pznQylFkSMSa9RwFrrg03HM0U8o',
    appId: '1:407000492909:ios:6812796a78389ef4df8864',
    messagingSenderId: '407000492909',
    projectId: 'studyquest-fb520',
    storageBucket: 'studyquest-fb520.firebasestorage.app',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr9XtBTdIkCaz9_x7ihuLLCefNDzH3VKE',
    appId: '1:407000492909:web:7ef8a497d115c849df8864',
    messagingSenderId: '407000492909',
    projectId: 'studyquest-fb520',
    authDomain: 'studyquest-fb520.firebaseapp.com',
    storageBucket: 'studyquest-fb520.firebasestorage.app',
  );
}
